# Generated by Django 4.1.2 on 2022-10-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("curriculum", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="DegreeInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree_name", models.CharField(max_length=20)),
                ("university_name", models.CharField(max_length=20)),
                ("start_year", models.DateField()),
                ("end_year", models.DateField()),
                ("certificate", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fName", models.CharField(max_length=20)),
                ("lName", models.CharField(max_length=20)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "MALE"),
                            ("FEMALE", "FEMALE"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(max_length=10)),
                ("profile_description", models.TextField(max_length=500)),
                ("years_of_experience", models.IntegerField()),
                ("location", models.JSONField()),
                ("profile_picture", models.ImageField(upload_to="")),
                ("curriculum", models.ManyToManyField(to="home.curriculum")),
                ("degrees", models.ManyToManyField(to="home.degreeinformation")),
                ("subjects", models.ManyToManyField(to="home.subject")),
            ],
        ),
    ]
