# Generated by Django 4.1.2 on 2022-10-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_message"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Message",
            new_name="UserMessage",
        ),
    ]
