# Generated by Django 4.1.2 on 2022-10-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_triallesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermessage",
            name="name",
            field=models.CharField(default="name", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usermessage",
            name="number",
            field=models.CharField(default="name", max_length=50),
            preserve_default=False,
        ),
    ]
