# Generated by Django 4.1.2 on 2022-10-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_triallesson_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermessage",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="home.tutor",
            ),
        ),
    ]
