# Generated by Django 4.1.2 on 2022-11-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_curriculum_options_alter_triallesson_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="location_name",
            field=models.CharField(default="pabna sadar", max_length=300),
            preserve_default=False,
        ),
    ]
