# Generated by Django 4.1.2 on 2022-11-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_degreeinformation_degree_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="degreeinformation",
            name="degree_name",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="degreeinformation",
            name="university_name",
            field=models.CharField(max_length=80),
        ),
    ]
