# Generated by Django 4.1.2 on 2022-11-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_alter_degreeinformation_degree_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="location_name",
            field=models.CharField(default="Location Name", max_length=300),
        ),
    ]
